#!/usr/bin/env python3
"""Prepare the app's input. Stdlib only; the app itself never opens SQLite.

    python3 tools/export.py NOTES.sqlite [THEME_MAP.md]

writes data/notes.jsonl and, given a theme map, data/themes.jsonl. Both are
gitignored: they are the owner's unpublished material and reach the image
from the working directory, never from git.

The format is what the framework's flat JSON reader can read: one object
per line, EVERY value a string, multi-valued fields joined with `|`.

    note   id note keywords source date type institution era comment entered
    theme  n title tension notes        (`notes` = row ids joined with `|`)

Anything this script would have to guess at is refused by name, because
the database and the map are both regenerated by other tools.
"""
import json, os, re, sqlite3, sys

SEP = "|"
MULTI = re.compile(r"[\n\r\x0b]+")  # FileMaker's repeating-value separators


def die(msg):
    sys.exit("export: " + msg)


def multi(row_id, field, value):
    parts = [p.strip() for p in MULTI.split(value or "") if p.strip()]
    for p in parts:
        if SEP in p:
            die("row %d: %s value %r holds the separator %r" % (row_id, field, p, SEP))
    return SEP.join(parts)


def century(row_id, yy):
    """The notes were typed 1995-2001. A two-digit year outside 90-10 is refused."""
    if yy >= 90:
        return 1900 + yy
    if yy <= 10:
        return 2000 + yy
    die("row %d: a two-digit year %02d is neither 199x nor 200x" % (row_id, yy))


def entered(row_id, slashed, squeezed):
    """ISO date a note was typed in. `slashed` (M/D/YY or M/D/YYYY) wins;
    `squeezed` is the same date without the slashes (52495 = 5/24/95). A
    slashed date that is a typo is reported and left blank -- it is metadata,
    and one bad cell should not hold back 534 notes -- but the squeezed shape
    that reads two ways is refused, because guessing there is silent."""
    slashed, squeezed = (slashed or "").strip(), (squeezed or "").strip()
    m = re.fullmatch(r"(\d{1,2})/(\d{1,2})/(\d{2}|(?:19|20)\d{2})", slashed)
    if m:
        mo, d, y = map(int, m.groups())
        year = y if y > 99 else century(row_id, y)
    elif squeezed:
        if not re.fullmatch(r"\d{4,6}", squeezed):
            die("row %d: squeezed date %r is not 4-6 digits" % (row_id, squeezed))
        if len(squeezed) == 5 and squeezed[0] == "1":
            # 1/DD/YY or 1M/D/YY: nothing in the value says which.
            die("row %d: squeezed date %r is ambiguous (1/DD or 1M/D)" % (row_id, squeezed))
        body, year = squeezed[:-2], century(row_id, int(squeezed[-2:]))
        mo, d = {2: (body[0], body[1]), 3: (body[0], body[1:]), 4: (body[:2], body[2:])}[len(body)]
        mo, d = int(mo), int(d)
    else:
        if slashed:
            print("export: WARNING row %d: entered date %r is not a date; left blank" % (row_id, slashed))
        return ""
    if not (1 <= mo <= 12 and 1 <= d <= 31):
        die("row %d: entered date %r/%r is not a date" % (row_id, slashed, squeezed))
    return "%04d-%02d-%02d" % (year, mo, d)


def export_notes(db_path, out):
    db = sqlite3.connect("file:%s?mode=ro" % db_path, uri=True)
    kw = {}
    for nid, term in db.execute("SELECT nk.note_id, k.term FROM note_keyword nk"
                                " JOIN keyword k ON k.id = nk.keyword_id ORDER BY k.term"):
        kw.setdefault(nid, []).append(term)
    ids = set()
    with open(out, "w", encoding="utf-8") as f:
        for r in db.execute("SELECT row_id, note, source, date, type, institution, era,"
                            " field_6, field_7, field_13 FROM notes ORDER BY row_id"):
            rid = r[0]
            ids.add(rid)
            comment = (r[8] or "").strip()
            comment = comment[2:].strip() if comment.startswith("::") else comment
            rec = {
                "id": str(rid), "note": (r[1] or "").strip(),
                "keywords": multi(rid, "keyword", "\n".join(kw.get(rid, []))),
                "source": (r[2] or "").strip(), "date": (r[3] or "").strip(),
                "type": multi(rid, "type", r[4]), "institution": multi(rid, "institution", r[5]),
                "era": multi(rid, "era", r[6]), "comment": comment,
                "entered": entered(rid, r[9], r[7]),
            }
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    return ids


def export_themes(md_path, ids, out):
    text = open(md_path, encoding="utf-8").read().split("\n# ", 1)[0]  # themes end at the next H1
    sections = re.split(r"(?m)^## (?=\d+\. )", text)[1:]
    if not sections:
        die("%s has no `## N. Title` sections" % md_path)
    with open(out, "w", encoding="utf-8") as f:
        for sec in sections:
            n, title = re.match(r"(\d+)\. (.+)", sec).groups()
            tension = re.search(r"(?m)^\*\*Tension\.\*\*\s*(.+)$", sec)
            cited = re.search(r"(?m)^\*\*Research notes\.\*\*\s*(.+)$", sec)
            if not tension or not cited:
                die("theme %s lacks a **Tension.** or **Research notes.** paragraph" % n)
            notes = []
            for a, b in re.findall(r"\[(\d+)\](?:\s*[–-]\s*\[(\d+)\])?", cited.group(1)):
                for rid in range(int(a), int(b or a) + 1):
                    if rid not in ids:
                        die("theme %s cites [%d], which is not a note" % (n, rid))
                    if rid not in notes:
                        notes.append(rid)
            rec = {"n": n, "title": title.strip(),
                   "tension": re.sub(r"[*_]", "", tension.group(1)).strip(),
                   "notes": SEP.join(map(str, notes))}
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    return len(sections)


if __name__ == "__main__":
    if len(sys.argv) not in (2, 3):
        sys.exit(__doc__)
    os.makedirs("data", exist_ok=True)
    ids = export_notes(sys.argv[1], "data/notes.jsonl")
    print("export: %d notes -> data/notes.jsonl" % len(ids))
    if len(sys.argv) == 3:
        print("export: %d themes -> data/themes.jsonl" % export_themes(sys.argv[2], ids, "data/themes.jsonl"))
