"""Where the corpus comes from: the owner's `notes.sqlite` and
`theme-map.md`, read at startup by the rules `tools/export.py` applied when
it turned them into JSON lines. This module is that script, moved into the
app, and the corpus it builds is the one the export wrote, byte for byte
(SOAK_LOG.md, the export step, dropped).

The database is opened READ-ONLY (`open_readonly`: never created, never
written, its journal mode left alone), because it is the owner's working
database and other tools rebuild it. A path ending in `.sql` is a script
instead: `data/sample.sql`, the invented sample, run into a private
in-memory database, so the repository holds no notes and no binary.

Anything the data would make this module guess at is refused, by row or
by theme number, as the export refused it: the database and the map are
both regenerated by other tools, and a note silently missing is worse than
a server that did not start. Where Python's rules shaped the export's
output — `str.strip()`'s whitespace, `\\s` in a pattern — they are kept, not
approximated.

No HTTP in this file: every function here is reachable by `uv run m0 test`.
"""

from m0_sqlite import Connection, Statement, open_memory, open_readonly

from corpus import Corpus

comptime NOTES_QUERY = (
    "SELECT row_id, note, source, date, type, institution, era,"
    " field_6, field_7, field_13 FROM notes ORDER BY row_id"
)
"""`field_7` is the comment; `field_13` is the date a note was entered, as
M/D/YY or M/D/YYYY, and `field_6` the same date squeezed (52495 = 5/24/95)."""

comptime KEYWORDS_QUERY = (
    "SELECT nk.note_id, k.term FROM note_keyword nk"
    " JOIN keyword k ON k.id = nk.keyword_id ORDER BY nk.note_id, k.term"
)
"""A note's keywords in term order, the notes in id order, so one pass
beside `NOTES_QUERY` hands each note its own."""

comptime TENSION_LABEL = "**Tension.**"
comptime CITED_LABEL = "**Research notes.**"
comptime EN_DASH = "–"
comptime MAX_ID_DIGITS = 9


# --- text, by Python's rules ---------------------------------------------------


def _space_at(b: Span[UInt8, _], i: Int, end: Int) -> Int:
    """The byte length of the whitespace character at `i`, else 0.

    Python's `str.isspace()` set, which `str.strip()` and a pattern's `\\s`
    both use: tab through carriage return, the four information separators,
    space, and fourteen characters above 0x7F. Mojo's `strip()` knows the
    ASCII ones alone, and FileMaker ends a field with a non-breaking space
    often enough to matter.
    """
    var c = b[i]
    if (c >= 9 and c <= 13) or (c >= 28 and c <= 32):
        return 1
    if c == 0xC2:
        if i + 1 < end and (b[i + 1] == 0x85 or b[i + 1] == 0xA0):
            return 2  # U+0085, U+00A0
        return 0
    if i + 2 >= end:
        return 0
    var d = b[i + 1]
    var e = b[i + 2]
    if c == 0xE1 and d == 0x9A and e == 0x80:
        return 3  # U+1680
    if c == 0xE2 and d == 0x80 and (
        (e >= 0x80 and e <= 0x8A) or e == 0xA8 or e == 0xA9 or e == 0xAF
    ):
        return 3  # U+2000–U+200A, U+2028, U+2029, U+202F
    if c == 0xE2 and d == 0x81 and e == 0x9F:
        return 3  # U+205F
    if c == 0xE3 and d == 0x80 and e == 0x80:
        return 3  # U+3000
    return 0


def _skip_space(b: Span[UInt8, _], start: Int, end: Int) -> Int:
    var i = start
    while i < end:
        var n = _space_at(b, i, end)
        if n == 0:
            break
        i += n
    return i


def strip_space(s: String) -> String:
    """`s` without leading or trailing whitespace, as `str.strip()` removes
    it. `s` must be UTF-8: a character is only ever removed whole."""
    var b = s.as_bytes()
    var start = _skip_space(b, 0, len(b))
    var end = len(b)
    while end > start:
        if _space_at(b, end - 1, end) == 1:
            end -= 1
        elif end - 2 >= start and _space_at(b, end - 2, end) == 2:
            end -= 2
        elif end - 3 >= start and _space_at(b, end - 3, end) == 3:
            end -= 3
        else:
            break
    if start == 0 and end == len(b):
        return s
    return String(unsafe_from_utf8=b[start:end])


def repeating(value: String) -> List[String]:
    """A FileMaker repeating field's values: split at every run of line
    feeds, carriage returns and vertical tabs, each value stripped, the
    empty ones dropped. `type`, `institution` and `era` all repeat."""
    var out = List[String]()
    var b = value.as_bytes()
    var start = 0
    for i in range(len(b) + 1):
        if i == len(b) or b[i] == 10 or b[i] == 13 or b[i] == 11:
            if i > start:
                var part = strip_space(String(unsafe_from_utf8=b[start:i]))
                if part.byte_length() > 0:
                    out.append(part^)
            start = i + 1
    return out^


def _is_digit(c: UInt8) -> Bool:
    return c >= 48 and c <= 57


def _digits(b: Span[UInt8, _], start: Int, end: Int) -> Bool:
    """Whether `b[start:end]` is one or more ASCII digits."""
    if start >= end:
        return False
    for i in range(start, end):
        if not _is_digit(b[i]):
            return False
    return True


def _number(b: Span[UInt8, _], start: Int, end: Int) -> Int:
    """`b[start:end]`, all digits and at most `MAX_ID_DIGITS` of them."""
    var n = 0
    for i in range(start, end):
        n = n * 10 + Int(b[i] - 48)
    return n


def _padded(n: Int, width: Int) -> String:
    var s = String(n)
    while s.byte_length() < width:
        s = String("0", s)
    return s^


# --- the notes database --------------------------------------------------------


def century(row: Int, yy: Int) raises -> Int:
    """The notes were typed from 1995 to 2001, so a two-digit year is 199x
    or 200x, and one outside 90–10 is refused."""
    if yy >= 90:
        return 1900 + yy
    if yy <= 10:
        return 2000 + yy
    raise Error(String(
        "row ", row, ": a two-digit year ", _padded(yy, 2), " is neither 199x nor 200x"
    ))


def _slashed_date(b: Span[UInt8, _]) -> Bool:
    """Whether `b` is M/D/YY or M/D/YYYY with the year 19xx or 20xx: one or
    two digits, a slash, one or two digits, a slash, the year, and nothing
    else."""
    var first = -1
    var second = -1
    for i in range(len(b)):
        if b[i] == 47:
            if first < 0:
                first = i
            elif second < 0:
                second = i
            else:
                return False
    if first < 1 or first > 2 or second - first < 2 or second - first > 3:
        return False
    if not _digits(b, 0, first) or not _digits(b, first + 1, second):
        return False
    var year = len(b) - second - 1
    if not _digits(b, second + 1, len(b)):
        return False
    if year == 2:
        return True
    if year != 4:
        return False
    var c0 = b[second + 1]
    var c1 = b[second + 2]
    return (c0 == 49 and c1 == 57) or (c0 == 50 and c1 == 48)


def entered_date(
    row: Int, slashed_text: String, squeezed_text: String, mut warnings: List[String]
) raises -> String:
    """The ISO date a note was typed in, or "".

    The slashed form (`field_13`) wins; the squeezed one (`field_6`) is the
    same date without the slashes. A slashed date that is a typo, with no
    squeezed twin, is reported in `warnings` and left blank — it is
    metadata, and one bad cell should not hold back 534 notes (row 520's
    `8/1/999`). The squeezed shape that reads two ways, five digits opening
    with 1, is refused, because guessing there is silent.
    """
    var slashed = strip_space(slashed_text)
    var squeezed = strip_space(squeezed_text)
    var month: Int
    var day: Int
    var year: Int
    var b = slashed.as_bytes()
    if _slashed_date(b):
        var first = 0
        while b[first] != 47:
            first += 1
        var second = first + 1
        while b[second] != 47:
            second += 1
        month = _number(b, 0, first)
        day = _number(b, first + 1, second)
        var y = _number(b, second + 1, len(b))
        year = y if y > 99 else century(row, y)
    elif squeezed.byte_length() > 0:
        var s = squeezed.as_bytes()
        var n = len(s)
        if n < 4 or n > 6 or not _digits(s, 0, n):
            raise Error(String(
                "row ", row, ": squeezed date '", squeezed, "' is not 4-6 digits"
            ))
        if n == 5 and s[0] == 49:
            raise Error(String(
                "row ", row, ": squeezed date '", squeezed,
                "' is ambiguous (1/DD or 1M/D)",
            ))
        year = century(row, _number(s, n - 2, n))
        if n == 4:
            month = _number(s, 0, 1)
            day = _number(s, 1, 2)
        elif n == 5:
            month = _number(s, 0, 1)
            day = _number(s, 1, 3)
        else:
            month = _number(s, 0, 2)
            day = _number(s, 2, 4)
    else:
        if slashed.byte_length() > 0:
            warnings.append(String(
                "row ", row, ": entered date '", slashed, "' is not a date; left blank"
            ))
        return String("")
    if month < 1 or month > 12 or day < 1 or day > 31:
        raise Error(String(
            "row ", row, ": entered date '", slashed, "'/'", squeezed, "' is not a date"
        ))
    return String(_padded(year, 4), "-", _padded(month, 2), "-", _padded(day, 2))


def comment_of(raw: String) -> String:
    """A comment without the `::` some of them open with."""
    var comment = strip_space(raw)
    if comment.startswith("::"):
        return strip_space(String(unsafe_from_utf8=comment.as_bytes()[2:]))
    return comment^


def _text(q: Statement, column: Int, row: Int, name: String) raises -> String:
    """A TEXT column, "" for NULL, refused by row when it is not UTF-8:
    SQLite keeps whatever bytes it was handed, and a `String` that is not
    UTF-8 is a trap in every page that renders it."""
    var raw = q.column_text(column)
    try:
        return String(from_utf8=raw.as_bytes())
    except:
        raise Error(String("row ", row, ": ", name, " is not UTF-8"))


def read_notes(db: Connection, mut corpus: Corpus) raises:
    """Every note, in `row_id` order, each with its keywords in term order.
    A keyword row naming no note is not anyone's keyword, and is skipped."""
    var keyword_notes = List[Int]()
    var keyword_terms = List[String]()
    var k = db.prepare(KEYWORDS_QUERY)
    while k.step():
        var id = k.column_int(0)
        keyword_notes.append(id)
        keyword_terms.append(_text(k, 1, id, "a keyword"))
    var j = 0
    var q = db.prepare(NOTES_QUERY)
    while q.step():
        var id = q.column_int(0)
        while j < len(keyword_notes) and keyword_notes[j] < id:
            j += 1
        var keywords = List[String]()
        while j < len(keyword_notes) and keyword_notes[j] == id:
            for term in repeating(keyword_terms[j]):
                keywords.append(term)
            j += 1
        var entered = entered_date(
            id, _text(q, 9, id, "field_13"), _text(q, 7, id, "field_6"), corpus.warnings
        )
        corpus.add_note(
            id,
            note=strip_space(_text(q, 1, id, "note")),
            source=strip_space(_text(q, 2, id, "source")),
            date=strip_space(_text(q, 3, id, "date")),
            comment=comment_of(_text(q, 8, id, "field_7")),
            entered=entered^,
            keywords=keywords^,
            kinds=repeating(_text(q, 4, id, "type")),
            institutions=repeating(_text(q, 5, id, "institution")),
            eras=repeating(_text(q, 6, id, "era")),
        )


def open_notes(path: String) raises -> Connection:
    """The notes database at `path`, read-only. A `.sql` path is a script,
    run into a private in-memory database: the invented sample."""
    if path.endswith(".jsonl"):
        raise Error(
            "this is tools/export.py's output, which unotes no longer reads:"
            " name the notes database (notes.sqlite) instead"
        )
    if path.endswith(".sql"):
        var db = open_memory()
        db.execute(_read_file(path))
        return db^
    return open_readonly(path)


# --- the theme map -------------------------------------------------------------


def _at(b: Span[UInt8, _], i: Int, end: Int, prefix: String) -> Bool:
    """Whether `b[i:end]` opens with `prefix`."""
    var p = prefix.as_bytes()
    if i + len(p) > end:
        return False
    for k in range(len(p)):
        if b[i + k] != p[k]:
            return False
    return True


def _line_end(b: Span[UInt8, _], i: Int, end: Int) -> Int:
    """The index of the line feed that ends the line holding `i`, or `end`."""
    var k = i
    while k < end and b[k] != 10:
        k += 1
    return k


def _theme_opens(b: Span[UInt8, _], i: Int, end: Int) -> Bool:
    """Whether the line at `i` is `## ` then a number then `. `."""
    if not _at(b, i, end, "## "):
        return False
    var d = i + 3
    while d < end and _is_digit(b[d]):
        d += 1
    return d > i + 3 and d + 1 < end and b[d] == 46 and b[d + 1] == 32


def _paragraph(b: Span[UInt8, _], start: Int, end: Int, label: String) -> Int:
    """Where the text after `label` starts, `label` opening the first line
    in `b[start:end]` that it opens; -1 if none does, or nothing follows it.
    Whitespace after the label is skipped, a line break included, as the
    export's `\\s*` skipped it; the text runs to the end of its line."""
    var i = start
    while i < end:
        if _at(b, i, end, label):
            var p = _skip_space(b, i + label.byte_length(), end)
            return p if p < end else -1
        i = _line_end(b, i, end) + 1
    return -1


def _cited_id(b: Span[UInt8, _], start: Int, end: Int, theme: Int) raises -> Int:
    if end - start > MAX_ID_DIGITS:
        raise Error(String(
            "theme ", theme, " cites [",
            String(unsafe_from_utf8=b[start:end]), "], which is not a note",
        ))
    return _number(b, start, end)


def _bracket_end(b: Span[UInt8, _], i: Int, end: Int) -> Int:
    """If `b[i:]` opens with `[`, digits and `]`, the index of the `]`."""
    if i >= end or b[i] != 91:
        return -1
    var k = i + 1
    while k < end and _is_digit(b[k]):
        k += 1
    if k > i + 1 and k < end and b[k] == 93:
        return k
    return -1


def _read_theme(b: Span[UInt8, _], start: Int, end: Int, mut corpus: Corpus) raises:
    """One section: `N. Title` on its first line, then the paragraphs."""
    var d = start
    while d < end and _is_digit(b[d]):
        d += 1
    if d - start > MAX_ID_DIGITS:
        raise Error("a theme's number is too long to be one")
    var n = _number(b, start, d)
    var title = strip_space(String(unsafe_from_utf8=b[d + 2 : _line_end(b, d + 2, end)]))
    if title.byte_length() == 0:
        raise Error(String("theme ", n, " has no title"))
    var t = _paragraph(b, start, end, TENSION_LABEL)
    var c = _paragraph(b, start, end, CITED_LABEL)
    if t < 0 or c < 0:
        raise Error(String(
            "theme ", n, " lacks a ", TENSION_LABEL, " or ", CITED_LABEL, " paragraph"
        ))
    # The tension, without the emphasis marks.
    var kept = List[UInt8]()
    for i in range(t, _line_end(b, t, end)):
        if b[i] != 42 and b[i] != 95:
            kept.append(b[i])
    var tension = strip_space(String(unsafe_from_utf8=Span(kept)))
    # The citations: [N], and [N]–[M] with an en dash or a hyphen, the ids
    # being `notes.row_id`. A number outside brackets is prose ("some 40
    # notes, 1890s–1930s").
    var cited = List[Int]()
    var stop = _line_end(b, c, end)
    var p = c
    while p < stop:
        var close = _bracket_end(b, p, stop)
        if close < 0:
            p += 1
            continue
        var first = _cited_id(b, p + 1, close, n)
        var last = first
        p = close + 1
        var r = _skip_space(b, p, stop)
        var dash = 0
        if r < stop and b[r] == 45:
            dash = 1
        elif _at(b, r, stop, EN_DASH):
            dash = EN_DASH.byte_length()
        if dash > 0:
            var s = _skip_space(b, r + dash, stop)
            var close2 = _bracket_end(b, s, stop)
            if close2 >= 0:
                last = _cited_id(b, s + 1, close2, n)
                p = close2 + 1
        if last < first:
            raise Error(String(
                "theme ", n, " cites [", first, "]–[", last, "], which runs backwards"
            ))
        for id in range(first, last + 1):
            if corpus.find(id) < 0:
                raise Error(String("theme ", n, " cites [", id, "], which is not a note"))
            var seen = False
            for k in range(len(cited)):
                if cited[k] == id:
                    seen = True
                    break
            if not seen:
                cited.append(id)
    corpus.add_theme(n, title^, tension^, cited^)


def read_theme_map(text: String, mut corpus: Corpus) raises:
    """Every theme in the map, into `corpus`, whose notes must already be
    in it: a theme citing a note that is not one is refused.

    The themes end at the first H1 after the title (`\\n# `): what follows,
    the anomalies and the gaps, is not a theme. A theme is a `## N. Title`
    heading and everything up to the next one; a heading without a number
    is part of the theme before it.
    """
    try:
        _ = String(from_utf8=text.as_bytes())
    except:
        raise Error("the theme map is not UTF-8")
    var b = text.as_bytes()
    var end = len(b)
    for i in range(len(b)):
        if _at(b, i, len(b), "\n# "):
            end = i
            break
    var opens = List[Int]()
    var i = 0
    while i < end:
        if _theme_opens(b, i, end):
            opens.append(i + 3)
        i = _line_end(b, i, end) + 1
    if len(opens) == 0:
        raise Error("no `## N. Title` sections")
    for s in range(len(opens)):
        var stop = opens[s + 1] - 3 if s + 1 < len(opens) else end
        _read_theme(b, opens[s], stop, corpus)


# --- both ----------------------------------------------------------------------


def _read_file(path: String) raises -> String:
    with open(path, "r") as f:
        return f.read()


def load_corpus(notes_path: String, themes_path: String) raises -> Corpus:
    """The notes, and the themes when `themes_path` is not empty; or an
    error naming the file, and in it the row or the theme."""
    var corpus = Corpus()
    try:
        var db = open_notes(notes_path)
        read_notes(db, corpus)
    except e:
        raise Error(String(notes_path, ": ", e))
    if len(corpus) == 0:
        raise Error(String(notes_path, ": no notes in it"))
    if themes_path.byte_length() > 0:
        try:
            read_theme_map(_read_file(themes_path), corpus)
        except e:
            raise Error(String(themes_path, ": ", e))
    corpus.finish()
    return corpus^
